#! /bin/sh

# Launch keybinding daemon
sxhkd &

# Start xautolock daemon
[ ! "`pgrep -u $USER xautolock`" ] && xautolock -locker "i3lock -de -I 5 -c 2d2d2d" -time 10 &

# Start Terminal daemon
[ ! "`pgrep -u $USER urxvtd`" ] && urxvtd --quiet --opendisplay &

# Start Udisks-glue for device automonting
[ ! "`pgrep -u $USER udisks-glue`" ] && udisks-glue &

# Launch panel
~/.config/bspwm/scripts/panel &
