#! /bin/sh

bspc config border_width        2
bspc config window_gap          5
bspc config top_padding         5

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       true

bspc monitor --reset-desktops main www dev chat edit play virt 8 9

bspc rule --add Iceweasel desktop=^2 follow=on
bspc rule --add Gimp desktop=^5 follow=on
bspc rule --add mplayer2 floating=on

# Autostart
~/.config/bspwm/autostart &
