#! /bin/sh

bspc config border_width        1
bspc config window_gap          10
bspc config top_padding         0

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config auto_cancel                 true

bspc monitor --reset-desktops main www dev chat edit play virt 8 9 10

bspc rule --add Iceweasel desktop=^2 follow=on
bspc rule --add Gimp desktop=^5 follow=on
bspc rule --add mplayer2 floating=on

# Colors
. ~/.config/bspwm/colors.cfg
bspc config focused_border_color                $bold_white
bspc config active_border_color                 $bold_white
bspc config normal_border_color                 $black
bspc config urgent_border_color                 $magenta
bspc config presel_border_color                 $blue

# Set wallpaper
hsetroot -tile ~/Imágenes/pattern

# Autostart
~/.config/bspwm/autostart &
