#!/bin/sh

# Launch systray
[ ! "`pgrep -u $USER stalonetray`" ] && stalonetray --config $BSPWM_CONFIG/stalonetrayrc &
# Hide systray after 5 seconds
(sleep 5s && xdotool search --class "stalonetray" windowunmap) &

# Start xautolock daemon
[ ! "`pgrep -u $USER xautolock`" ] && xautolock -locker "i3lock -de -I 5 -c 2d2d2d" -time 10 &

# Start Terminal daemon
[ ! "`pgrep -u $USER urxvtd`" ] && urxvtd --quiet --opendisplay &

# Start Udisks-glue for device automonting
[ ! "`pgrep -u $USER udisks-glue`" ] && udisks-glue &

# Start Update-notifier
update-notifier &
# Start ownCloud client
owncloud &
# Start clipboard manager
parcellite &
# Start Empathy
empathy --start-hidden &
# Start Workrave
workrave &
# Start lightsOn script
~/bin/lightsOn.sh 300 &

# Hot corners
# Activate screensaver
xdotool behave_screen_edge --quiesce 600 --delay 0 top-right \
    exec --sync xautolock -locknow &
# Toggle visibility of systray
xdotool behave_screen_edge --quiesce 600 --delay 0 bottom-right \
    exec --sync $BSPWM_CONFIG/scripts/toggle-systray &
