#!/bin/sh

# Set environment
export BSPWM_CONFIG="$HOME/.config/bspwm"

bspc config border_width        2
bspc config window_gap          20
bspc config top_padding         0

bspc config split_ratio                 0.60
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config auto_cancel                 true

bspc monitor --reset-desktops term www dev chat edit play virt 8 9 10

# Make windows float on specific desktops
bspc desktop ^6 --toggle floating=on
bspc desktop ^7 --toggle floating=on
bspc desktop ^9 --toggle floating=on

# Send to www desktop
bspc rule --add Iceweasel desktop=^2 --one-shot follow=on
# Send to dev desktop
bspc rule --add Atom desktop=^3 follow=on
bspc rule --add Brackets desktop=^3 follow=on
bspc rule --add Eclipse desktop=^3 follow=on
bspc rule --add Ltbin desktop=^3 follow=on
bspc rule --add Gvim desktop=^3 follow=on
bspc rule --add sun-awt-X11-XFramePeer desktop=^3 follow=on
# Send to chat desktop
bspc rule --add Hexchat desktop=^4 --one-shot follow=on
bspc rule --add Xchat desktop=^4 --one-shot follow=on
# Send to edit desktop
bspc rule --add Abiword desktop=^5 follow=on
bspc rule --add Avidemux desktop=^5 follow=on
bspc rule --add Blender desktop=^5 follow=on
bspc rule --add Darktable desktop=^5 follow=on
bspc rule --add Gimp desktop=^5 follow=on
bspc rule --add Gnumeric desktop=^5 follow=on
bspc rule --add Handbrake desktop=^5 follow=on
bspc rule --add Illustrator.exe desktop=^5 follow=on
bspc rule --add Inkscape desktop=^5 follow=on
bspc rule --add libreoffice desktop=^5 follow=on
bspc rule --add Openshot desktop=^5 follow=on
bspc rule --add Pitivi desktop=^5 follow=on
bspc rule --add Rawtherapee desktop=^5 follow=on
bspc rule --add Ufraw desktop=^5 follow=on
# Send to play desktop
bspc rule --add Desura desktop=^6
bspc rule --add Popcorn-time desktop=^6
bspc rule --add scummvm desktop=^6
bspc rule --add Steam desktop=^6
# Send to virt desktop
bspc rule --add VirtualBox desktop=^7
bspc rule --add Virt-manager desktop=^7
# Floating windows
bspc rule --add Htop floating=on
bspc rule --add Mixer floating=on
bspc rule --add MPC floating=on
bspc rule --add Mutt floating=on
bspc rule --add scratchpad sticky=on floating=on
bspc rule --add Display floating=on
bspc rule --add Empathy floating=on
bspc rule --add Eog floating=on
bspc rule --add feh floating=on
bspc rule --add Keepassx floating=on
bspc rule --add mplayer2 floating=on
bspc rule --add mpv floating=on
bspc rule --add Nautilus floating=on
bspc rule --add Pavucontrol floating=on
bspc rule --add Pidgin floating=on
bspc rule --add qTox floating=on
bspc rule --add Remmina floating=on
bspc rule --add "Syncthing GTK" floating=on
bspc rule --add Transmission-gtk floating=on
bspc rule --add Uget-gtk floating=on
bspc rule --add Vinagre floating=on
bspc rule --add Vlc floating=on

# Colors
. $BSPWM_CONFIG/colors.cfg
bspc config focused_border_color                $brightwhite
bspc config active_border_color                 $brightblack
bspc config normal_border_color                 $black
bspc config urgent_border_color                 $blue
bspc config presel_border_color                 $yellow
bspc config focused_locked_border_color         $brightred
bspc config active_locked_border_color          $red
bspc config normal_locked_border_color          $black
bspc config focused_sticky_border_color         $brightcyan
bspc config active_sticky_border_color          $cyan
bspc config normal_sticky_border_color          $black
bspc config focused_private_border_color        $brightblue
bspc config active_private_border_color         $blue
bspc config normal_private_border_color         $black

# Set wallpaper
hsetroot -tile ~/Imágenes/pattern

# Load session
. $BSPWM_CONFIG/restore.cfg
if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

# Launch keybinding daemon
sxhkd &

# Launch panel
$BSPWM_CONFIG/scripts/panel &

# Autostart
$BSPWM_CONFIG/autostart &
