#!/bin/sh

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

# Function to kill programs
killprogs() {
	# Kill udisks-glue
	pkill -x udisks-glue
	# Kill panel
	pkill -x panel
	# Kill Redshift
	pkill -x redshift
}

# Restart function
restart() {
	# Save session status
	. "$BSPWM_CONFIG/restore.cfg"
	bspc query -T > "$BSPWM_TREE"
	bspc query -H > "$BSPWM_HISTORY"
	bspc query -S > "$BSPWM_STACK"
	# Kill programs
	killprogs
	# Quit bspwm
	bspc quit 0
}

# Logout function
logout() {
	# For each opened window
	bspc query --windows | while read -r winid; do
		# Close it
		xdotool windowkill "$winid"
	done
	# Kill programs
	killprogs
	# Quit bspwm
	bspc quit 1
}

# Load dmenu config
[ -f "$HOME/.dmenurc" ] && . "$HOME/.dmenurc" || DMENU='dmenu -i'

# Menu items
items="restart
logout
hibernate
suspend
reboot
poweroff"

# Open menu
selection=$(printf '%s' "$items" | $DMENU)

case $selection in
	restart)
		restart
		;;
	logout)
		logout
		;;
	hibernate)
		dbus-send --system --print-reply --dest="org.freedesktop.DeviceKit.Power" /org/freedesktop/DeviceKit/Power org.freedesktop.DeviceKit.Power.Hibernate
		;;
	suspend)
		dbus-send --system --print-reply --dest="org.freedesktop.DeviceKit.Power" /org/freedesktop/DeviceKit/Power org.freedesktop.DeviceKit.Power.Suspend
		;;
	reboot)
		logout
		dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
		;;
	halt|poweroff|shutdown)
		logout
		dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
		;;
esac

exit
