#!/bin/sh
#
# Example panel for LemonBoy's bar

. "$BSPWM_CONFIG/panel.cfg"

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		SYS*)
			# system info output
			sys_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		NET*)
			# netowrk info output
			net_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		PWR*)
			# power info output
			pwr_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		CLK*)
			# date info output
			clk_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		VOL*)
			# volume info output
			vol_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		KBD*)
			# kbd info output
			kbd_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		MPD*)
			# mpd info output
			mpd_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		OWM*)
			# weather info output
			owm_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		TSK*)
			# todo info output
			tsk_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		MSG*)
			# mail info output
			msg_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#???}%{B-}%{F-}"
			;;
		TTL*)
			# title output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#???} %{B-}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}%{A4:bspc monitor --focus prev.occupied:}%{A5:bspc monitor --focus next.occupied:} ${name} %{A}%{A}%{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos
							%{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}%{A:bspc monitor --focus ${name}:}%{A4:bspc monitor --focus prev.occupied:}%{A5:bspc monitor --focus next.occupied:} ${name} %{A}%{A}%{A}%{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_UNDERLINE}%{+u}%{A4:bspc desktop --focus prev.occupied:}%{A5:bspc desktop --focus next.occupied:} ${name} %{A}%{A}%{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_UNDERLINE}%{+u}%{A4:bspc desktop --focus prev.occupied:}%{A5:bspc desktop --focus next.occupied:} ${name} %{A}%{A}%{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_UNDERLINE}%{+u}%{A4:bspc desktop --focus prev.occupied:}%{A5:bspc desktop --focus next.occupied:} ${name} %{A}%{A}%{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}%{A1:bspc desktop --focus ${name}:}%{A4:bspc desktop --focus prev.occupied:}%{A5:bspc desktop --focus next.occupied:} ${name} %{A}%{A}%{A}%{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}%{A1:bspc desktop --focus ${name}:}%{A4:bspc desktop --focus prev.occupied:}%{A5:bspc desktop --focus next.occupied:} ${name} %{A}%{A}%{A}%{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{r}${mpd_info}${kbd_info}${vol_info}${pwr_info}${clk_info}%{l}${wm_infos}${title}"
done

exit
# vim: set ts=8 sw=8 tw=0 noet :
